apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegram-forwarder.fullname" . }}
  labels:
    app: {{ include "telegram-forwarder.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "telegram-forwarder.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "telegram-forwarder.name" . }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          secret:
            secretName: {{ .Values.configSecret.name }}
