{{- if .Values.configSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecret.name }}
type: Opaque
data:
  config.yaml: {{ tpl .Values.configSecret.template (dict "Values" .Values) | b64enc | quote }}
{{- end }}
