replicaCount: 1

image:
  repository: ghcr.io/pufferfish-io/telegram-forwarder
  tag: v0.1.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  hosts:
    - host: tg.forwarder.pufferfish.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - tg.forwarder.pufferfish.ru
      secretName: tg-forwarder-tls

configSecret:
  enabled: true
  name: telegram-forwarder-config

  template: |
    telegram:
      token: {{ .Values.telegramToken }}
    kafka:
      bootstrap_servers_value: localhost:9092
    server:
      port: 8080

telegramToken: ""
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
