name: Deploy Kafka to K3s

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Load .env into environment
        run: |
          set -a
          source infra/.env
          set +a

      - name: Deploy Kafka via helmfile
        run: |
          cd infra
          helmfile -e production apply
