name: Deploy Kafka to K3s

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: 🔧 Load .env into environment
        run: |
          set -a
          source infra/.env
          set +a

      - name: 🧠 Debug: print env
        run: |
          echo "KAFKA_CLUSTER_ID = $KAFKA_CLUSTER_ID"

      - name: 🚀 Deploy Kafka via helmfile
        run: |
          cd infra
          helmfile -e production apply
