name: Deploy Kafka to K3s

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: ☕ Kafka Deployment
    runs-on: self-hosted

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: 🧃 Load .env manually into environment
        run: |
          grep -v '^#' infra/.env >> $GITHUB_ENV

      - name: 🧠 Print env for debug
        run: echo "KAFKA_CLUSTER_ID = $KAFKA_CLUSTER_ID"

      - name: 🧷 Set kubeconfig path for K3s
        run: echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

      - name: 🛠 Test cluster connection (optional)
        run: kubectl get nodes

      - name: 📥 Install helm-diff plugin
        run: helm plugin install https://github.com/databus23/helm-diff || true

      - name: 🚀 Deploy Kafka via helmfile
        run: |
          cd infra
          helmfile -e production apply --debug