name: Deploy Kafka to K3s

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: 🧃 Load .env manually into environment
        run: |
          grep -v '^#' infra/.env >> $GITHUB_ENV

      - name: 🚀 Deploy Kafka via helmfile
        run: |
          cd infra
          helmfile -e production apply