name: "📜 Logs Go deployment"

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: "Deployment name (service name)"
        required: true
        type: choice
        options:
          - telegram-forwarder
          - telegram-normalizer
          - message-responder
          - tg-response-preparer
      since:
        description: "Show logs since (e.g. 10m, 1h)"
        required: false
        type: string
        default: "10m"
      tail:
        description: "Number of lines to show"
        required: false
        type: string
        default: "300"
      duration_seconds:
        description: "When following, stop after N seconds"
        required: false
        type: string
        default: "0"
jobs:
  logs:
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      DEPLOYMENT: ${{ github.event.inputs.deployment }}
      SINCE: ${{ github.event.inputs.since }}
      TAIL: ${{ github.event.inputs.tail }}
      DURATION_SECONDS: ${{ github.event.inputs.duration_seconds }}
    steps:
      - name: 📡 Show logs (snapshot or follow)
        continue-on-error: true
        run: |
          set -e
          echo "Target deployment: ${DEPLOYMENT} (ns: app)"
          echo "Options: since=${SINCE:-10m} tail=${TAIL:-300} follow_seconds=${DURATION_SECONDS:-0}"

          if [ -n "${DURATION_SECONDS}" ] && [ "${DURATION_SECONDS}" != "0" ]; then
            echo "⏳ Following logs with timeout ${DURATION_SECONDS}s"
            if command -v timeout >/dev/null 2>&1; then
              set +e
              timeout -k 5s "${DURATION_SECONDS}s" \
                kubectl -n app logs deploy/"${DEPLOYMENT}" --tail="${TAIL:-300}" -f
              status=$?
              set -e
              if [ "$status" -ne 0 ] && [ "$status" -ne 124 ]; then
                echo "❌ kubectl logs exited with code $status"
                exit "$status"
              fi
              echo "⏹️  Stopped following after ${DURATION_SECONDS}s"
            else
              echo "⚠️  'timeout' not found; showing snapshot (no follow)"
              kubectl -n app logs deploy/"${DEPLOYMENT}" --tail="${TAIL:-300}"
            fi
          else
            echo "🧾 Snapshot logs since ${SINCE} (tail ${TAIL})"
            kubectl -n app logs deploy/"${DEPLOYMENT}" --since="${SINCE:-10m}" --tail="${TAIL:-300}"
          fi
