name: "🩺 Monitor Go logs"

on:
  schedule:
    - cron: "0 3 * * *" # daily at 03:00 UTC
  workflow_dispatch:
    inputs:
      deployment:
        description: "Deployment name (default: telegram-forwarder)"
        required: false

jobs:
  check:
    runs-on: self-hosted
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - name: ✅ Tail last log line (strict TLS)
        run: |
          set -euo pipefail
          NAME="${{ github.event.inputs.deployment }}"
          if [ -z "${NAME:-}" ]; then NAME="telegram-forwarder"; fi
          echo "Checking logs for deployment: $NAME (ns: app)"
          kubectl -n app get deploy "$NAME" >/dev/null
          if ! kubectl -n app logs deploy/"$NAME" --tail=1 >/dev/null 2>&1; then
            echo "❌ Failed to fetch logs for $NAME"
            echo "--- Deployment describe ---"
            kubectl -n app describe deploy "$NAME" || true
            echo "--- Pods ---"
            kubectl -n app get pods -l app="$NAME" -o wide || true
            echo "--- Recent events ---"
            kubectl -n app get events --sort-by=.lastTimestamp | tail -n 20 || true
            exit 1
          fi
          echo "✅ OK: logs tail fetched."

